ddescribe("Proper monk", function () {
  it("should do kung fu", function () {
    App.socket.trigger('progress', [{
      browser: 'Chrome 36.0.1985 (Mac OS X 10.9.4)',
      progress: {
        failed: 1,
        tested: 5,
      },
    }]);
    expect($('.browser-status').html()).toBe('1/5');
  });
  
  it("should create good karma", function () {
    
  });
  
  it("reports test results in real-time", function () {});
  it("supports full keyboard navigation", function () {
    sinon.spy(App.fold, 'goDown');
    $(document.body).trigger($.Event( "keypress", { keyCode: 106 } ));
    expect(App.fold.goDown).toHaveBeenCalled();
    App.fold.goDown.restore();
  });
});

describe("Pseudo Module", function () {
  it("should be", function () { expect(1).toBe(2); });
  
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("should be", function () { expect(1).toBe(2); });
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  
  it("should be", function () { expect(1).toBe(2); });
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("should be", function () { expect(1).toBe(2); });
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("should be", function () { expect(1).toBe(2); });
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  it("reports test results in real-time", function () {});
  
});
